CPP = c++
SRC = Base.cpp main.cpp
HEAD = Base.hpp A.hpp B.hpp C.hpp
NAME = base
FLAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(SRC) $(HEAD)
	$(CPP) $(FLAGS) $(SRC) -o $(NAME)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re: fclean $(NAME)